#!/usr/bin/env sh

# directory containing NetCDF files
inputdir="$HOME/data/0_original"
# directory to put JPEG files
outputdir="$HOME/data/1_jpeg"
# quality
quality=60
# python from current environment
PYTHON="/usr/bin/env python"

# auto-setting variables
inputdir="${1:-$inputdir}"
outputdir="${2:-$outputdir}"
quality="${3:-$quality}"

[ ! -d "$inputdir" ] && echo Input dir does not exist! && exit 1
[ ! -d "$outputdir" ] && mkdir -p $outputdir

for file in $inputdir/*
do
  outfile="$outputdir/$(basename $file)"
  dir="$(dirname $outfile)"
  outfilename="$(basename $outfile)"
  outname="${outfilename%.*}"
  [ $(echo "$outfilename" | grep "\." 2>/dev/null) ] && outext=".${outfilename##*.}"
  [ $outext = ".nc" ] && outext=".jpg"
  [ -z $outext ]      && outext=".jpg"
  outfile="$dir/$outname$outext"

  echo "### Converting ###"
  echo "# $file"
  echo "# to"
  echo "# $outfile"
  echo "##################"
  [ -f $file ] && $PYTHON nc2jpg/nc2jpg.py $file -o $outfile -q $quality
done
